/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisSession {
  'availableStablecoins' : Array<string>,
  'csvFile' : ExternalBlob,
  'assetStats' : Array<AssetStats>,
  'user' : Principal,
  'availableMetals' : Array<string>,
  'stablecoinStats' : Array<AssetStats>,
  'summary' : TradeSummary,
  'cryptoStats' : Array<AssetStats>,
  'feeOverview' : [] | [FeeOverview],
  'availableAssets' : Array<string>,
  'metalsStats' : Array<AssetStats>,
  'timestamp' : bigint,
  'sessionId' : string,
  'positions' : Array<TradePosition>,
}
export type AssetCategoryEnum = { 'metal' : null } |
  { 'stablecoin' : null } |
  { 'other' : null } |
  { 'crypto' : null } |
  { 'commodity' : null };
export interface AssetStats {
  'tradeCount' : bigint,
  'totalPnl' : number,
  'averagePnl' : number,
  'positions' : Array<TradePosition>,
  'symbol' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeeAssetAnalysis {
  'asset' : string,
  'tradeCount' : bigint,
  'percentageOfTotal' : number,
  'totalFees' : number,
}
export interface FeeCategoryAnalysis {
  'categoryName' : string,
  'tradeCount' : bigint,
  'percentageOfTotal' : number,
  'totalFees' : number,
}
export interface FeeDirectionAnalysis {
  'direction' : TradeDirectionEnum,
  'tradeCount' : bigint,
  'percentageOfTotal' : number,
  'totalFees' : number,
}
export interface FeeOverview {
  'feesByDirection' : Array<FeeDirectionAnalysis>,
  'topTradesByFee' : Array<TopTradeByFee>,
  'recommendations' : Array<string>,
  'totalFees' : number,
  'averageFee' : number,
  'feesByCategory' : Array<FeeCategoryAnalysis>,
  'feesByAsset' : Array<FeeAssetAnalysis>,
}
export type PositionStatus = { 'pending' : null } |
  { 'safe' : null } |
  { 'liquidated' : null } |
  { 'atRisk' : null };
export type Principal = Principal;
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'extreme' : null } |
  { 'medium' : null };
export interface TopTradeByFee {
  'feeAmount' : number,
  'context' : string,
  'asset' : string,
  'tradeId' : string,
}
export type TradeDirectionEnum = { 'long' : null } |
  { 'short' : null };
export interface TradePosition {
  'fee' : number,
  'status' : PositionStatus,
  'direction' : TradeDirectionEnum,
  'leverage' : [] | [number],
  'user' : string,
  'positionSize' : number,
  'isLiquidated' : boolean,
  'liquidationPrice' : [] | [number],
  'tradeId' : string,
  'marginUsed' : number,
  'realizedPnl' : number,
  'entryPrice' : number,
  'unrealizedPnl' : number,
  'assetCategory' : AssetCategoryEnum,
  'riskLevel' : RiskLevel,
  'symbol' : string,
}
export interface TradeSummary {
  'averageRiskLevel' : RiskLevel,
  'liquidatedPositions' : bigint,
  'totalMetalsPnl' : number,
  'totalPnl' : number,
  'totalMargin' : number,
  'totalPositions' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'calculateDynamicLeverage' : ActorMethod<
    [
      string,
      [] | [AssetCategoryEnum],
      number,
      number,
      [] | [number],
      [] | [number],
      [] | [number],
    ],
    [] | [number]
  >,
  'deleteSession' : ActorMethod<[string], undefined>,
  'getAllMetals' : ActorMethod<[], Array<string>>,
  'getAllSessions' : ActorMethod<[], Array<AnalysisSession>>,
  'getAllStablecoins' : ActorMethod<[], Array<string>>,
  'getAssetStats' : ActorMethod<
    [string, [] | [AssetCategoryEnum]],
    [Array<AssetStats>, Array<AssetStats>]
  >,
  'getAverageInterestRates' : ActorMethod<
    [string],
    [] | [
      {
        'averageWeeklyRate' : number,
        'averageDailyRate' : number,
        'averageMonthlyRate' : number,
      }
    ]
  >,
  'getCryptoLeverage' : ActorMethod<[string], number>,
  'getDefaultCryptoLeverage' : ActorMethod<[], number>,
  'getDefaultLeverage' : ActorMethod<[AssetCategoryEnum], number>,
  'getDefaultMetalsLeverage' : ActorMethod<[], number>,
  'getDefaultStablecoinLeverage' : ActorMethod<[], number>,
  'getFeeOverview' : ActorMethod<[string], [] | [FeeOverview]>,
  'getHyperliquidOrderBook' : ActorMethod<[string], [] | [string]>,
  'getKursDeviation' : ActorMethod<
    [string],
    [] | [{ 'deviation' : number, 'sellPrice' : number, 'buyPrice' : number }]
  >,
  'getLegacyClosestLeverage' : ActorMethod<
    [string, number, AssetCategoryEnum],
    number
  >,
  'getLegacyUniqueTradeSymbols' : ActorMethod<[], Array<string>>,
  'getLeverageStats' : ActorMethod<
    [string, AssetCategoryEnum],
    {
      'defaultLeverage' : number,
      'minLeverage' : number,
      'maxLeverage' : number,
      'mostFrequentLeverage' : number,
    }
  >,
  'getMetalLeverage' : ActorMethod<[string], number>,
  'getSession' : ActorMethod<[string], AnalysisSession>,
  'getSessionAvailableAssets' : ActorMethod<[string], Array<string>>,
  'getStablecoinLeverage' : ActorMethod<[string], number>,
  'getUserSessions' : ActorMethod<[Principal], Array<AnalysisSession>>,
  'storeAnalysisSession' : ActorMethod<
    [
      string,
      Principal,
      ExternalBlob,
      Array<TradePosition>,
      TradeSummary,
      Array<AssetStats>,
      Array<AssetStats>,
      Array<AssetStats>,
      Array<AssetStats>,
      Array<string>,
      Array<string>,
      Array<string>,
      bigint,
      [] | [FeeOverview],
    ],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];