/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AssetCategoryEnum = IDL.Variant({
  'metal' : IDL.Null,
  'stablecoin' : IDL.Null,
  'other' : IDL.Null,
  'crypto' : IDL.Null,
  'commodity' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PositionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'safe' : IDL.Null,
  'liquidated' : IDL.Null,
  'atRisk' : IDL.Null,
});
export const TradeDirectionEnum = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'extreme' : IDL.Null,
  'medium' : IDL.Null,
});
export const TradePosition = IDL.Record({
  'fee' : IDL.Float64,
  'status' : PositionStatus,
  'direction' : TradeDirectionEnum,
  'leverage' : IDL.Opt(IDL.Float64),
  'user' : IDL.Text,
  'positionSize' : IDL.Float64,
  'isLiquidated' : IDL.Bool,
  'liquidationPrice' : IDL.Opt(IDL.Float64),
  'tradeId' : IDL.Text,
  'marginUsed' : IDL.Float64,
  'realizedPnl' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'unrealizedPnl' : IDL.Float64,
  'assetCategory' : AssetCategoryEnum,
  'riskLevel' : RiskLevel,
  'symbol' : IDL.Text,
});
export const AssetStats = IDL.Record({
  'tradeCount' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'averagePnl' : IDL.Float64,
  'positions' : IDL.Vec(TradePosition),
  'symbol' : IDL.Text,
});
export const Principal = IDL.Principal;
export const TradeSummary = IDL.Record({
  'averageRiskLevel' : RiskLevel,
  'liquidatedPositions' : IDL.Nat,
  'totalMetalsPnl' : IDL.Float64,
  'totalPnl' : IDL.Float64,
  'totalMargin' : IDL.Float64,
  'totalPositions' : IDL.Nat,
});
export const FeeDirectionAnalysis = IDL.Record({
  'direction' : TradeDirectionEnum,
  'tradeCount' : IDL.Nat,
  'percentageOfTotal' : IDL.Float64,
  'totalFees' : IDL.Float64,
});
export const TopTradeByFee = IDL.Record({
  'feeAmount' : IDL.Float64,
  'context' : IDL.Text,
  'asset' : IDL.Text,
  'tradeId' : IDL.Text,
});
export const FeeCategoryAnalysis = IDL.Record({
  'categoryName' : IDL.Text,
  'tradeCount' : IDL.Nat,
  'percentageOfTotal' : IDL.Float64,
  'totalFees' : IDL.Float64,
});
export const FeeAssetAnalysis = IDL.Record({
  'asset' : IDL.Text,
  'tradeCount' : IDL.Nat,
  'percentageOfTotal' : IDL.Float64,
  'totalFees' : IDL.Float64,
});
export const FeeOverview = IDL.Record({
  'feesByDirection' : IDL.Vec(FeeDirectionAnalysis),
  'topTradesByFee' : IDL.Vec(TopTradeByFee),
  'recommendations' : IDL.Vec(IDL.Text),
  'totalFees' : IDL.Float64,
  'averageFee' : IDL.Float64,
  'feesByCategory' : IDL.Vec(FeeCategoryAnalysis),
  'feesByAsset' : IDL.Vec(FeeAssetAnalysis),
});
export const AnalysisSession = IDL.Record({
  'availableStablecoins' : IDL.Vec(IDL.Text),
  'csvFile' : ExternalBlob,
  'assetStats' : IDL.Vec(AssetStats),
  'user' : Principal,
  'availableMetals' : IDL.Vec(IDL.Text),
  'stablecoinStats' : IDL.Vec(AssetStats),
  'summary' : TradeSummary,
  'cryptoStats' : IDL.Vec(AssetStats),
  'feeOverview' : IDL.Opt(FeeOverview),
  'availableAssets' : IDL.Vec(IDL.Text),
  'metalsStats' : IDL.Vec(AssetStats),
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'positions' : IDL.Vec(TradePosition),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'calculateDynamicLeverage' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(AssetCategoryEnum),
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Opt(IDL.Float64)],
      [],
    ),
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'getAllMetals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(AnalysisSession)], ['query']),
  'getAllStablecoins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAssetStats' : IDL.Func(
      [IDL.Text, IDL.Opt(AssetCategoryEnum)],
      [IDL.Vec(AssetStats), IDL.Vec(AssetStats)],
      ['query'],
    ),
  'getAverageInterestRates' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'averageWeeklyRate' : IDL.Float64,
            'averageDailyRate' : IDL.Float64,
            'averageMonthlyRate' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getCryptoLeverage' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getDefaultCryptoLeverage' : IDL.Func([], [IDL.Float64], ['query']),
  'getDefaultLeverage' : IDL.Func(
      [AssetCategoryEnum],
      [IDL.Float64],
      ['query'],
    ),
  'getDefaultMetalsLeverage' : IDL.Func([], [IDL.Float64], ['query']),
  'getDefaultStablecoinLeverage' : IDL.Func([], [IDL.Float64], ['query']),
  'getFeeOverview' : IDL.Func([IDL.Text], [IDL.Opt(FeeOverview)], ['query']),
  'getHyperliquidOrderBook' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getKursDeviation' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'deviation' : IDL.Float64,
            'sellPrice' : IDL.Float64,
            'buyPrice' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getLegacyClosestLeverage' : IDL.Func(
      [IDL.Text, IDL.Float64, AssetCategoryEnum],
      [IDL.Float64],
      ['query'],
    ),
  'getLegacyUniqueTradeSymbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLeverageStats' : IDL.Func(
      [IDL.Text, AssetCategoryEnum],
      [
        IDL.Record({
          'defaultLeverage' : IDL.Float64,
          'minLeverage' : IDL.Float64,
          'maxLeverage' : IDL.Float64,
          'mostFrequentLeverage' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMetalLeverage' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getSession' : IDL.Func([IDL.Text], [AnalysisSession], ['query']),
  'getSessionAvailableAssets' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getStablecoinLeverage' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getUserSessions' : IDL.Func(
      [Principal],
      [IDL.Vec(AnalysisSession)],
      ['query'],
    ),
  'storeAnalysisSession' : IDL.Func(
      [
        IDL.Text,
        Principal,
        ExternalBlob,
        IDL.Vec(TradePosition),
        TradeSummary,
        IDL.Vec(AssetStats),
        IDL.Vec(AssetStats),
        IDL.Vec(AssetStats),
        IDL.Vec(AssetStats),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Int,
        IDL.Opt(FeeOverview),
      ],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AssetCategoryEnum = IDL.Variant({
    'metal' : IDL.Null,
    'stablecoin' : IDL.Null,
    'other' : IDL.Null,
    'crypto' : IDL.Null,
    'commodity' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PositionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'safe' : IDL.Null,
    'liquidated' : IDL.Null,
    'atRisk' : IDL.Null,
  });
  const TradeDirectionEnum = IDL.Variant({
    'long' : IDL.Null,
    'short' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'extreme' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TradePosition = IDL.Record({
    'fee' : IDL.Float64,
    'status' : PositionStatus,
    'direction' : TradeDirectionEnum,
    'leverage' : IDL.Opt(IDL.Float64),
    'user' : IDL.Text,
    'positionSize' : IDL.Float64,
    'isLiquidated' : IDL.Bool,
    'liquidationPrice' : IDL.Opt(IDL.Float64),
    'tradeId' : IDL.Text,
    'marginUsed' : IDL.Float64,
    'realizedPnl' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'unrealizedPnl' : IDL.Float64,
    'assetCategory' : AssetCategoryEnum,
    'riskLevel' : RiskLevel,
    'symbol' : IDL.Text,
  });
  const AssetStats = IDL.Record({
    'tradeCount' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'averagePnl' : IDL.Float64,
    'positions' : IDL.Vec(TradePosition),
    'symbol' : IDL.Text,
  });
  const Principal = IDL.Principal;
  const TradeSummary = IDL.Record({
    'averageRiskLevel' : RiskLevel,
    'liquidatedPositions' : IDL.Nat,
    'totalMetalsPnl' : IDL.Float64,
    'totalPnl' : IDL.Float64,
    'totalMargin' : IDL.Float64,
    'totalPositions' : IDL.Nat,
  });
  const FeeDirectionAnalysis = IDL.Record({
    'direction' : TradeDirectionEnum,
    'tradeCount' : IDL.Nat,
    'percentageOfTotal' : IDL.Float64,
    'totalFees' : IDL.Float64,
  });
  const TopTradeByFee = IDL.Record({
    'feeAmount' : IDL.Float64,
    'context' : IDL.Text,
    'asset' : IDL.Text,
    'tradeId' : IDL.Text,
  });
  const FeeCategoryAnalysis = IDL.Record({
    'categoryName' : IDL.Text,
    'tradeCount' : IDL.Nat,
    'percentageOfTotal' : IDL.Float64,
    'totalFees' : IDL.Float64,
  });
  const FeeAssetAnalysis = IDL.Record({
    'asset' : IDL.Text,
    'tradeCount' : IDL.Nat,
    'percentageOfTotal' : IDL.Float64,
    'totalFees' : IDL.Float64,
  });
  const FeeOverview = IDL.Record({
    'feesByDirection' : IDL.Vec(FeeDirectionAnalysis),
    'topTradesByFee' : IDL.Vec(TopTradeByFee),
    'recommendations' : IDL.Vec(IDL.Text),
    'totalFees' : IDL.Float64,
    'averageFee' : IDL.Float64,
    'feesByCategory' : IDL.Vec(FeeCategoryAnalysis),
    'feesByAsset' : IDL.Vec(FeeAssetAnalysis),
  });
  const AnalysisSession = IDL.Record({
    'availableStablecoins' : IDL.Vec(IDL.Text),
    'csvFile' : ExternalBlob,
    'assetStats' : IDL.Vec(AssetStats),
    'user' : Principal,
    'availableMetals' : IDL.Vec(IDL.Text),
    'stablecoinStats' : IDL.Vec(AssetStats),
    'summary' : TradeSummary,
    'cryptoStats' : IDL.Vec(AssetStats),
    'feeOverview' : IDL.Opt(FeeOverview),
    'availableAssets' : IDL.Vec(IDL.Text),
    'metalsStats' : IDL.Vec(AssetStats),
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'positions' : IDL.Vec(TradePosition),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'calculateDynamicLeverage' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(AssetCategoryEnum),
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Opt(IDL.Float64)],
        [],
      ),
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'getAllMetals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(AnalysisSession)], ['query']),
    'getAllStablecoins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAssetStats' : IDL.Func(
        [IDL.Text, IDL.Opt(AssetCategoryEnum)],
        [IDL.Vec(AssetStats), IDL.Vec(AssetStats)],
        ['query'],
      ),
    'getAverageInterestRates' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'averageWeeklyRate' : IDL.Float64,
              'averageDailyRate' : IDL.Float64,
              'averageMonthlyRate' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getCryptoLeverage' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getDefaultCryptoLeverage' : IDL.Func([], [IDL.Float64], ['query']),
    'getDefaultLeverage' : IDL.Func(
        [AssetCategoryEnum],
        [IDL.Float64],
        ['query'],
      ),
    'getDefaultMetalsLeverage' : IDL.Func([], [IDL.Float64], ['query']),
    'getDefaultStablecoinLeverage' : IDL.Func([], [IDL.Float64], ['query']),
    'getFeeOverview' : IDL.Func([IDL.Text], [IDL.Opt(FeeOverview)], ['query']),
    'getHyperliquidOrderBook' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getKursDeviation' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'deviation' : IDL.Float64,
              'sellPrice' : IDL.Float64,
              'buyPrice' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getLegacyClosestLeverage' : IDL.Func(
        [IDL.Text, IDL.Float64, AssetCategoryEnum],
        [IDL.Float64],
        ['query'],
      ),
    'getLegacyUniqueTradeSymbols' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getLeverageStats' : IDL.Func(
        [IDL.Text, AssetCategoryEnum],
        [
          IDL.Record({
            'defaultLeverage' : IDL.Float64,
            'minLeverage' : IDL.Float64,
            'maxLeverage' : IDL.Float64,
            'mostFrequentLeverage' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMetalLeverage' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getSession' : IDL.Func([IDL.Text], [AnalysisSession], ['query']),
    'getSessionAvailableAssets' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getStablecoinLeverage' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getUserSessions' : IDL.Func(
        [Principal],
        [IDL.Vec(AnalysisSession)],
        ['query'],
      ),
    'storeAnalysisSession' : IDL.Func(
        [
          IDL.Text,
          Principal,
          ExternalBlob,
          IDL.Vec(TradePosition),
          TradeSummary,
          IDL.Vec(AssetStats),
          IDL.Vec(AssetStats),
          IDL.Vec(AssetStats),
          IDL.Vec(AssetStats),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Int,
          IDL.Opt(FeeOverview),
        ],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };