/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TradeSummary {
    averageRiskLevel: RiskLevel;
    liquidatedPositions: bigint;
    totalMetalsPnl: number;
    totalPnl: number;
    totalMargin: number;
    totalPositions: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FeeDirectionAnalysis {
    direction: TradeDirectionEnum;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
}
export type Principal = Principal;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FeeOverview {
    feesByDirection: Array<FeeDirectionAnalysis>;
    topTradesByFee: Array<TopTradeByFee>;
    recommendations: Array<string>;
    totalFees: number;
    averageFee: number;
    feesByCategory: Array<FeeCategoryAnalysis>;
    feesByAsset: Array<FeeAssetAnalysis>;
}
export interface AnalysisSession {
    availableStablecoins: Array<string>;
    csvFile: ExternalBlob;
    assetStats: Array<AssetStats>;
    user: Principal;
    availableMetals: Array<string>;
    stablecoinStats: Array<AssetStats>;
    summary: TradeSummary;
    cryptoStats: Array<AssetStats>;
    feeOverview?: FeeOverview;
    availableAssets: Array<string>;
    metalsStats: Array<AssetStats>;
    timestamp: bigint;
    sessionId: string;
    positions: Array<TradePosition>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TradePosition {
    fee: number;
    status: PositionStatus;
    direction: TradeDirectionEnum;
    leverage?: number;
    user: string;
    positionSize: number;
    isLiquidated: boolean;
    liquidationPrice?: number;
    tradeId: string;
    marginUsed: number;
    realizedPnl: number;
    entryPrice: number;
    unrealizedPnl: number;
    assetCategory: AssetCategoryEnum;
    riskLevel: RiskLevel;
    symbol: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FeeAssetAnalysis {
    asset: string;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FeeCategoryAnalysis {
    categoryName: string;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
}
export interface AssetStats {
    tradeCount: bigint;
    totalPnl: number;
    averagePnl: number;
    positions: Array<TradePosition>;
    symbol: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TopTradeByFee {
    feeAmount: number;
    context: string;
    asset: string;
    tradeId: string;
}
export enum AssetCategoryEnum {
    metal = "metal",
    stablecoin = "stablecoin",
    other = "other",
    crypto = "crypto",
    commodity = "commodity"
}
export enum PositionStatus {
    pending = "pending",
    safe = "safe",
    liquidated = "liquidated",
    atRisk = "atRisk"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    extreme = "extreme",
    medium = "medium"
}
export enum TradeDirectionEnum {
    long_ = "long",
    short_ = "short"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    calculateDynamicLeverage(_stablecoin: string, _assetCategory: AssetCategoryEnum | null, entryPrice: number, positionSize: number, marginUsed: number | null, ntl: number | null, fee: number | null): Promise<number | null>;
    deleteSession(sessionId: string): Promise<void>;
    getAllMetals(): Promise<Array<string>>;
    getAllSessions(): Promise<Array<AnalysisSession>>;
    getAllStablecoins(): Promise<Array<string>>;
    getAssetStats(sessionId: string, assetCategory: AssetCategoryEnum | null): Promise<[Array<AssetStats>, Array<AssetStats>]>;
    getAverageInterestRates(_asset: string): Promise<{
        averageWeeklyRate: number;
        averageDailyRate: number;
        averageMonthlyRate: number;
    } | null>;
    getCryptoLeverage(_crypto: string): Promise<number>;
    getDefaultCryptoLeverage(): Promise<number>;
    getDefaultLeverage(assetCategory: AssetCategoryEnum): Promise<number>;
    getDefaultMetalsLeverage(): Promise<number>;
    getDefaultStablecoinLeverage(): Promise<number>;
    getFeeOverview(sessionId: string): Promise<FeeOverview | null>;
    getHyperliquidOrderBook(symbol: string): Promise<string | null>;
    getKursDeviation(_metal: string): Promise<{
        deviation: number;
        sellPrice: number;
        buyPrice: number;
    } | null>;
    getLegacyClosestLeverage(_asset: string, leverage: number, _assetCategory: AssetCategoryEnum): Promise<number>;
    getLegacyUniqueTradeSymbols(): Promise<Array<string>>;
    getLeverageStats(_asset: string, _assetCategory: AssetCategoryEnum): Promise<{
        defaultLeverage: number;
        minLeverage: number;
        maxLeverage: number;
        mostFrequentLeverage: number;
    }>;
    getMetalLeverage(_metal: string): Promise<number>;
    getSession(sessionId: string): Promise<AnalysisSession>;
    getSessionAvailableAssets(sessionId: string): Promise<Array<string>>;
    getStablecoinLeverage(_stablecoin: string): Promise<number>;
    getUserSessions(user: Principal): Promise<Array<AnalysisSession>>;
    storeAnalysisSession(sessionId: string, user: Principal, csvFile: ExternalBlob, positions: Array<TradePosition>, summary: TradeSummary, assetStats: Array<AssetStats>, metalsStats: Array<AssetStats>, cryptoStats: Array<AssetStats>, stablecoinStats: Array<AssetStats>, availableAssets: Array<string>, availableMetals: Array<string>, availableStablecoins: Array<string>, timestamp: bigint, feeOverview: FeeOverview | null): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnalysisSession as _AnalysisSession, AssetCategoryEnum as _AssetCategoryEnum, AssetStats as _AssetStats, ExternalBlob as _ExternalBlob, FeeAssetAnalysis as _FeeAssetAnalysis, FeeCategoryAnalysis as _FeeCategoryAnalysis, FeeDirectionAnalysis as _FeeDirectionAnalysis, FeeOverview as _FeeOverview, PositionStatus as _PositionStatus, Principal as _Principal, RiskLevel as _RiskLevel, TopTradeByFee as _TopTradeByFee, TradeDirectionEnum as _TradeDirectionEnum, TradePosition as _TradePosition, TradeSummary as _TradeSummary, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async calculateDynamicLeverage(arg0: string, arg1: AssetCategoryEnum | null, arg2: number, arg3: number, arg4: number | null, arg5: number | null, arg6: number | null): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateDynamicLeverage(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6));
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateDynamicLeverage(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6));
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async getAllMetals(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMetals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMetals();
            return result;
        }
    }
    async getAllSessions(): Promise<Array<AnalysisSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStablecoins(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStablecoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStablecoins();
            return result;
        }
    }
    async getAssetStats(arg0: string, arg1: AssetCategoryEnum | null): Promise<[Array<AssetStats>, Array<AssetStats>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetStats(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return [
                    from_candid_vec_n17(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n17(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetStats(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return [
                from_candid_vec_n17(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n17(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getAverageInterestRates(arg0: string): Promise<{
        averageWeeklyRate: number;
        averageDailyRate: number;
        averageMonthlyRate: number;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageInterestRates(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageInterestRates(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoLeverage(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoLeverage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoLeverage(arg0);
            return result;
        }
    }
    async getDefaultCryptoLeverage(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultCryptoLeverage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultCryptoLeverage();
            return result;
        }
    }
    async getDefaultLeverage(arg0: AssetCategoryEnum): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultLeverage(to_candid_AssetCategoryEnum_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultLeverage(to_candid_AssetCategoryEnum_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDefaultMetalsLeverage(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultMetalsLeverage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultMetalsLeverage();
            return result;
        }
    }
    async getDefaultStablecoinLeverage(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultStablecoinLeverage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultStablecoinLeverage();
            return result;
        }
    }
    async getFeeOverview(arg0: string): Promise<FeeOverview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeOverview(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeOverview(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHyperliquidOrderBook(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHyperliquidOrderBook(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHyperliquidOrderBook(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKursDeviation(arg0: string): Promise<{
        deviation: number;
        sellPrice: number;
        buyPrice: number;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKursDeviation(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKursDeviation(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegacyClosestLeverage(arg0: string, arg1: number, arg2: AssetCategoryEnum): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegacyClosestLeverage(arg0, arg1, to_candid_AssetCategoryEnum_n9(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegacyClosestLeverage(arg0, arg1, to_candid_AssetCategoryEnum_n9(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getLegacyUniqueTradeSymbols(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegacyUniqueTradeSymbols();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegacyUniqueTradeSymbols();
            return result;
        }
    }
    async getLeverageStats(arg0: string, arg1: AssetCategoryEnum): Promise<{
        defaultLeverage: number;
        minLeverage: number;
        maxLeverage: number;
        mostFrequentLeverage: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeverageStats(arg0, to_candid_AssetCategoryEnum_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeverageStats(arg0, to_candid_AssetCategoryEnum_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getMetalLeverage(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetalLeverage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetalLeverage(arg0);
            return result;
        }
    }
    async getSession(arg0: string): Promise<AnalysisSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_AnalysisSession_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_AnalysisSession_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionAvailableAssets(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionAvailableAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionAvailableAssets(arg0);
            return result;
        }
    }
    async getStablecoinLeverage(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getStablecoinLeverage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStablecoinLeverage(arg0);
            return result;
        }
    }
    async getUserSessions(arg0: Principal): Promise<Array<AnalysisSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSessions(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSessions(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeAnalysisSession(arg0: string, arg1: Principal, arg2: ExternalBlob, arg3: Array<TradePosition>, arg4: TradeSummary, arg5: Array<AssetStats>, arg6: Array<AssetStats>, arg7: Array<AssetStats>, arg8: Array<AssetStats>, arg9: Array<string>, arg10: Array<string>, arg11: Array<string>, arg12: bigint, arg13: FeeOverview | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeAnalysisSession(arg0, arg1, await to_candid_ExternalBlob_n42(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n43(this._uploadFile, this._downloadFile, arg3), to_candid_TradeSummary_n52(this._uploadFile, this._downloadFile, arg4), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg5), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg7), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, to_candid_opt_n57(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeAnalysisSession(arg0, arg1, await to_candid_ExternalBlob_n42(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n43(this._uploadFile, this._downloadFile, arg3), to_candid_TradeSummary_n52(this._uploadFile, this._downloadFile, arg4), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg5), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg7), to_candid_vec_n54(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, to_candid_opt_n57(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
async function from_candid_AnalysisSession_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisSession): Promise<AnalysisSession> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_AssetCategoryEnum_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetCategoryEnum): AssetCategoryEnum {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_AssetStats_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetStats): AssetStats {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeeDirectionAnalysis_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeDirectionAnalysis): FeeDirectionAnalysis {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_FeeOverview_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeOverview): FeeOverview {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PositionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionStatus): PositionStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirectionEnum_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirectionEnum): TradeDirectionEnum {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TradePosition_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradePosition): TradePosition {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSummary_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSummary): TradeSummary {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeOverview]): FeeOverview | null {
    return value.length === 0 ? null : from_candid_FeeOverview_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        averageWeeklyRate: number;
        averageDailyRate: number;
        averageMonthlyRate: number;
    }]): {
    averageWeeklyRate: number;
    averageDailyRate: number;
    averageMonthlyRate: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        deviation: number;
        sellPrice: number;
        buyPrice: number;
    }]): {
    deviation: number;
    sellPrice: number;
    buyPrice: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    availableStablecoins: Array<string>;
    csvFile: _ExternalBlob;
    assetStats: Array<_AssetStats>;
    user: _Principal;
    availableMetals: Array<string>;
    stablecoinStats: Array<_AssetStats>;
    summary: _TradeSummary;
    cryptoStats: Array<_AssetStats>;
    feeOverview: [] | [_FeeOverview];
    availableAssets: Array<string>;
    metalsStats: Array<_AssetStats>;
    timestamp: bigint;
    sessionId: string;
    positions: Array<_TradePosition>;
}): Promise<{
    availableStablecoins: Array<string>;
    csvFile: ExternalBlob;
    assetStats: Array<AssetStats>;
    user: Principal;
    availableMetals: Array<string>;
    stablecoinStats: Array<AssetStats>;
    summary: TradeSummary;
    cryptoStats: Array<AssetStats>;
    feeOverview?: FeeOverview;
    availableAssets: Array<string>;
    metalsStats: Array<AssetStats>;
    timestamp: bigint;
    sessionId: string;
    positions: Array<TradePosition>;
}> {
    return {
        availableStablecoins: value.availableStablecoins,
        csvFile: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.csvFile),
        assetStats: from_candid_vec_n17(_uploadFile, _downloadFile, value.assetStats),
        user: value.user,
        availableMetals: value.availableMetals,
        stablecoinStats: from_candid_vec_n17(_uploadFile, _downloadFile, value.stablecoinStats),
        summary: from_candid_TradeSummary_n31(_uploadFile, _downloadFile, value.summary),
        cryptoStats: from_candid_vec_n17(_uploadFile, _downloadFile, value.cryptoStats),
        feeOverview: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.feeOverview)),
        availableAssets: value.availableAssets,
        metalsStats: from_candid_vec_n17(_uploadFile, _downloadFile, value.metalsStats),
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        positions: from_candid_vec_n20(_uploadFile, _downloadFile, value.positions)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeCount: bigint;
    totalPnl: number;
    averagePnl: number;
    positions: Array<_TradePosition>;
    symbol: string;
}): {
    tradeCount: bigint;
    totalPnl: number;
    averagePnl: number;
    positions: Array<TradePosition>;
    symbol: string;
} {
    return {
        tradeCount: value.tradeCount,
        totalPnl: value.totalPnl,
        averagePnl: value.averagePnl,
        positions: from_candid_vec_n20(_uploadFile, _downloadFile, value.positions),
        symbol: value.symbol
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fee: number;
    status: _PositionStatus;
    direction: _TradeDirectionEnum;
    leverage: [] | [number];
    user: string;
    positionSize: number;
    isLiquidated: boolean;
    liquidationPrice: [] | [number];
    tradeId: string;
    marginUsed: number;
    realizedPnl: number;
    entryPrice: number;
    unrealizedPnl: number;
    assetCategory: _AssetCategoryEnum;
    riskLevel: _RiskLevel;
    symbol: string;
}): {
    fee: number;
    status: PositionStatus;
    direction: TradeDirectionEnum;
    leverage?: number;
    user: string;
    positionSize: number;
    isLiquidated: boolean;
    liquidationPrice?: number;
    tradeId: string;
    marginUsed: number;
    realizedPnl: number;
    entryPrice: number;
    unrealizedPnl: number;
    assetCategory: AssetCategoryEnum;
    riskLevel: RiskLevel;
    symbol: string;
} {
    return {
        fee: value.fee,
        status: from_candid_PositionStatus_n23(_uploadFile, _downloadFile, value.status),
        direction: from_candid_TradeDirectionEnum_n25(_uploadFile, _downloadFile, value.direction),
        leverage: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.leverage)),
        user: value.user,
        positionSize: value.positionSize,
        isLiquidated: value.isLiquidated,
        liquidationPrice: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.liquidationPrice)),
        tradeId: value.tradeId,
        marginUsed: value.marginUsed,
        realizedPnl: value.realizedPnl,
        entryPrice: value.entryPrice,
        unrealizedPnl: value.unrealizedPnl,
        assetCategory: from_candid_AssetCategoryEnum_n27(_uploadFile, _downloadFile, value.assetCategory),
        riskLevel: from_candid_RiskLevel_n29(_uploadFile, _downloadFile, value.riskLevel),
        symbol: value.symbol
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageRiskLevel: _RiskLevel;
    liquidatedPositions: bigint;
    totalMetalsPnl: number;
    totalPnl: number;
    totalMargin: number;
    totalPositions: bigint;
}): {
    averageRiskLevel: RiskLevel;
    liquidatedPositions: bigint;
    totalMetalsPnl: number;
    totalPnl: number;
    totalMargin: number;
    totalPositions: bigint;
} {
    return {
        averageRiskLevel: from_candid_RiskLevel_n29(_uploadFile, _downloadFile, value.averageRiskLevel),
        liquidatedPositions: value.liquidatedPositions,
        totalMetalsPnl: value.totalMetalsPnl,
        totalPnl: value.totalPnl,
        totalMargin: value.totalMargin,
        totalPositions: value.totalPositions
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feesByDirection: Array<_FeeDirectionAnalysis>;
    topTradesByFee: Array<_TopTradeByFee>;
    recommendations: Array<string>;
    totalFees: number;
    averageFee: number;
    feesByCategory: Array<_FeeCategoryAnalysis>;
    feesByAsset: Array<_FeeAssetAnalysis>;
}): {
    feesByDirection: Array<FeeDirectionAnalysis>;
    topTradesByFee: Array<TopTradeByFee>;
    recommendations: Array<string>;
    totalFees: number;
    averageFee: number;
    feesByCategory: Array<FeeCategoryAnalysis>;
    feesByAsset: Array<FeeAssetAnalysis>;
} {
    return {
        feesByDirection: from_candid_vec_n36(_uploadFile, _downloadFile, value.feesByDirection),
        topTradesByFee: value.topTradesByFee,
        recommendations: value.recommendations,
        totalFees: value.totalFees,
        averageFee: value.averageFee,
        feesByCategory: value.feesByCategory,
        feesByAsset: value.feesByAsset
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _TradeDirectionEnum;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
}): {
    direction: TradeDirectionEnum;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
} {
    return {
        direction: from_candid_TradeDirectionEnum_n25(_uploadFile, _downloadFile, value.direction),
        tradeCount: value.tradeCount,
        percentageOfTotal: value.percentageOfTotal,
        totalFees: value.totalFees
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    safe: null;
} | {
    liquidated: null;
} | {
    atRisk: null;
}): PositionStatus {
    return "pending" in value ? PositionStatus.pending : "safe" in value ? PositionStatus.safe : "liquidated" in value ? PositionStatus.liquidated : "atRisk" in value ? PositionStatus.atRisk : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): TradeDirectionEnum {
    return "long" in value ? TradeDirectionEnum.long : "short" in value ? TradeDirectionEnum.short : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metal: null;
} | {
    stablecoin: null;
} | {
    other: null;
} | {
    crypto: null;
} | {
    commodity: null;
}): AssetCategoryEnum {
    return "metal" in value ? AssetCategoryEnum.metal : "stablecoin" in value ? AssetCategoryEnum.stablecoin : "other" in value ? AssetCategoryEnum.other : "crypto" in value ? AssetCategoryEnum.crypto : "commodity" in value ? AssetCategoryEnum.commodity : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    extreme: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "extreme" in value ? RiskLevel.extreme : "medium" in value ? RiskLevel.medium : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisSession>): Promise<Array<AnalysisSession>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnalysisSession_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetStats>): Array<AssetStats> {
    return value.map((x)=>from_candid_AssetStats_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradePosition>): Array<TradePosition> {
    return value.map((x)=>from_candid_TradePosition_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeDirectionAnalysis>): Array<FeeDirectionAnalysis> {
    return value.map((x)=>from_candid_FeeDirectionAnalysis_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AssetCategoryEnum_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategoryEnum): _AssetCategoryEnum {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_AssetStats_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStats): _AssetStats {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FeeDirectionAnalysis_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeDirectionAnalysis): _FeeDirectionAnalysis {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_FeeOverview_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeOverview): _FeeOverview {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_PositionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionStatus): _PositionStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_TradeDirectionEnum_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirectionEnum): _TradeDirectionEnum {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_TradePosition_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradePosition): _TradePosition {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_TradeSummary_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSummary): _TradeSummary {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeOverview | null): [] | [_FeeOverview] {
    return value === null ? candid_none() : candid_some(to_candid_FeeOverview_n58(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategoryEnum | null): [] | [_AssetCategoryEnum] {
    return value === null ? candid_none() : candid_some(to_candid_AssetCategoryEnum_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fee: number;
    status: PositionStatus;
    direction: TradeDirectionEnum;
    leverage?: number;
    user: string;
    positionSize: number;
    isLiquidated: boolean;
    liquidationPrice?: number;
    tradeId: string;
    marginUsed: number;
    realizedPnl: number;
    entryPrice: number;
    unrealizedPnl: number;
    assetCategory: AssetCategoryEnum;
    riskLevel: RiskLevel;
    symbol: string;
}): {
    fee: number;
    status: _PositionStatus;
    direction: _TradeDirectionEnum;
    leverage: [] | [number];
    user: string;
    positionSize: number;
    isLiquidated: boolean;
    liquidationPrice: [] | [number];
    tradeId: string;
    marginUsed: number;
    realizedPnl: number;
    entryPrice: number;
    unrealizedPnl: number;
    assetCategory: _AssetCategoryEnum;
    riskLevel: _RiskLevel;
    symbol: string;
} {
    return {
        fee: value.fee,
        status: to_candid_PositionStatus_n46(_uploadFile, _downloadFile, value.status),
        direction: to_candid_TradeDirectionEnum_n48(_uploadFile, _downloadFile, value.direction),
        leverage: value.leverage ? candid_some(value.leverage) : candid_none(),
        user: value.user,
        positionSize: value.positionSize,
        isLiquidated: value.isLiquidated,
        liquidationPrice: value.liquidationPrice ? candid_some(value.liquidationPrice) : candid_none(),
        tradeId: value.tradeId,
        marginUsed: value.marginUsed,
        realizedPnl: value.realizedPnl,
        entryPrice: value.entryPrice,
        unrealizedPnl: value.unrealizedPnl,
        assetCategory: to_candid_AssetCategoryEnum_n9(_uploadFile, _downloadFile, value.assetCategory),
        riskLevel: to_candid_RiskLevel_n50(_uploadFile, _downloadFile, value.riskLevel),
        symbol: value.symbol
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageRiskLevel: RiskLevel;
    liquidatedPositions: bigint;
    totalMetalsPnl: number;
    totalPnl: number;
    totalMargin: number;
    totalPositions: bigint;
}): {
    averageRiskLevel: _RiskLevel;
    liquidatedPositions: bigint;
    totalMetalsPnl: number;
    totalPnl: number;
    totalMargin: number;
    totalPositions: bigint;
} {
    return {
        averageRiskLevel: to_candid_RiskLevel_n50(_uploadFile, _downloadFile, value.averageRiskLevel),
        liquidatedPositions: value.liquidatedPositions,
        totalMetalsPnl: value.totalMetalsPnl,
        totalPnl: value.totalPnl,
        totalMargin: value.totalMargin,
        totalPositions: value.totalPositions
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeCount: bigint;
    totalPnl: number;
    averagePnl: number;
    positions: Array<TradePosition>;
    symbol: string;
}): {
    tradeCount: bigint;
    totalPnl: number;
    averagePnl: number;
    positions: Array<_TradePosition>;
    symbol: string;
} {
    return {
        tradeCount: value.tradeCount,
        totalPnl: value.totalPnl,
        averagePnl: value.averagePnl,
        positions: to_candid_vec_n43(_uploadFile, _downloadFile, value.positions),
        symbol: value.symbol
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feesByDirection: Array<FeeDirectionAnalysis>;
    topTradesByFee: Array<TopTradeByFee>;
    recommendations: Array<string>;
    totalFees: number;
    averageFee: number;
    feesByCategory: Array<FeeCategoryAnalysis>;
    feesByAsset: Array<FeeAssetAnalysis>;
}): {
    feesByDirection: Array<_FeeDirectionAnalysis>;
    topTradesByFee: Array<_TopTradeByFee>;
    recommendations: Array<string>;
    totalFees: number;
    averageFee: number;
    feesByCategory: Array<_FeeCategoryAnalysis>;
    feesByAsset: Array<_FeeAssetAnalysis>;
} {
    return {
        feesByDirection: to_candid_vec_n60(_uploadFile, _downloadFile, value.feesByDirection),
        topTradesByFee: value.topTradesByFee,
        recommendations: value.recommendations,
        totalFees: value.totalFees,
        averageFee: value.averageFee,
        feesByCategory: value.feesByCategory,
        feesByAsset: value.feesByAsset
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: TradeDirectionEnum;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
}): {
    direction: _TradeDirectionEnum;
    tradeCount: bigint;
    percentageOfTotal: number;
    totalFees: number;
} {
    return {
        direction: to_candid_TradeDirectionEnum_n48(_uploadFile, _downloadFile, value.direction),
        tradeCount: value.tradeCount,
        percentageOfTotal: value.percentageOfTotal,
        totalFees: value.totalFees
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategoryEnum): {
    metal: null;
} | {
    stablecoin: null;
} | {
    other: null;
} | {
    crypto: null;
} | {
    commodity: null;
} {
    return value == AssetCategoryEnum.metal ? {
        metal: null
    } : value == AssetCategoryEnum.stablecoin ? {
        stablecoin: null
    } : value == AssetCategoryEnum.other ? {
        other: null
    } : value == AssetCategoryEnum.crypto ? {
        crypto: null
    } : value == AssetCategoryEnum.commodity ? {
        commodity: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionStatus): {
    pending: null;
} | {
    safe: null;
} | {
    liquidated: null;
} | {
    atRisk: null;
} {
    return value == PositionStatus.pending ? {
        pending: null
    } : value == PositionStatus.safe ? {
        safe: null
    } : value == PositionStatus.liquidated ? {
        liquidated: null
    } : value == PositionStatus.atRisk ? {
        atRisk: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirectionEnum): {
    long: null;
} | {
    short: null;
} {
    return value == TradeDirectionEnum.long ? {
        long_: null
    } : value == TradeDirectionEnum.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    extreme: null;
} | {
    medium: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.extreme ? {
        extreme: null
    } : value == RiskLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TradePosition>): Array<_TradePosition> {
    return value.map((x)=>to_candid_TradePosition_n44(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AssetStats>): Array<_AssetStats> {
    return value.map((x)=>to_candid_AssetStats_n55(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FeeDirectionAnalysis>): Array<_FeeDirectionAnalysis> {
    return value.map((x)=>to_candid_FeeDirectionAnalysis_n61(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
